#!/bin/busybox sh

# Install symlinks to all busybox applets first.
/bin/busybox mkdir -p /usr/sbin /usr/bin /sbin /bin
/bin/busybox --install -s

# Mount /dev
mount -t devtmpfs none /dev

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys

# Do your stuff here.
echo "This script just mounts and boots the rootfs, nothing else!"

# Mount the root filesystem.
# mount -o ro /dev/sda1 /mnt/root


# run shell
exec sh

# Clean up.
umount /proc
umount /sys
umount /dev

# Boot the real thing.
#exec switch_root /mnt/root /sbin/init
