+incdir+$HW_dir/SRC/wb_bus/
+incdir+$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/
+incdir+$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/
+incdir+$HW_dir/SRC/can_master/
+incdir+$HW_dir/SRC/wb_bus/wb_common_1.0.1/
+incdir+$HW_dir/SRC/utils/verilog_utils_0/
+incdir+$HW_dir/SRC/ecc_bch_dec/src/rtl/univ/
+incdir+$HW_dir/TB/include
+incdir+$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/
$HW_dir/SRC/can_master/can_acf.v
//$HW_dir/SRC/wb_bus/wb_bfm_1.0/wb_bfm_master.v
//$HW_dir/SRC/wb_bus/wb_bfm_1.0/wb_bfm_memory.v
//$HW_dir/SRC/wb_bus/wb_bfm_1.0/wb_bfm_slave.v
//$HW_dir/SRC/wb_bus/wb_bfm_1.0/wb_bfm_transactor.v
$HW_dir/SRC/wb_bus/wb_common_1.0.1/wb_common.v
//$HW_dir/SRC/wb_bus/wb_common_1.0.1/wb_common_params.v
$HW_dir/SRC/wb_bus/wb_intercon.v
$HW_dir/SRC/wb_bus/wb_intercon_1.0/rtl/verilog/wb_arbiter.v
$HW_dir/SRC/wb_bus/wb_intercon_1.0/rtl/verilog/wb_data_resize.v
$HW_dir/SRC/wb_bus/wb_intercon_1.0/rtl/verilog/wb_mux.v
$HW_dir/SRC/wb_ram_1.0/rtl/verilog/wb_ram.v
$HW_dir/SRC/wb_ram_1.0/rtl/verilog/wb_ram_ecc.v
$HW_dir/SRC/wb_ram_1.0/rtl/verilog/wb_ram_generic.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_crc32.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_defines.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_jsp_biu.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_jsp_module.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_biu.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_defines.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_module.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_status_reg.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_top.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_biu.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_defines.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_module.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/bytefifo.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/syncflop.v
$HW_dir/SRC/adv_debug_sys_3.1.0/Hardware/adv_dbg_if/rtl/verilog/syncreg.v
$HW_dir/SRC/autosoc_top.v
$HW_dir/SRC/can_master/can_bsp.v
$HW_dir/SRC/can_master/can_btl.v
$HW_dir/SRC/can_master/can_crc.v
$HW_dir/SRC/can_master/can_defines.v
$HW_dir/SRC/can_master/can_fifo.v
$HW_dir/SRC/can_master/can_ibo.v
$HW_dir/SRC/can_master/can_register.v
$HW_dir/SRC/can_master/can_register_asyn.v
$HW_dir/SRC/can_master/can_register_asyn_syn.v
$HW_dir/SRC/can_master/can_registers.v
$HW_dir/SRC/can_master/can_top.v
$HW_dir/SRC/can_master/can_transceiver.v
$HW_dir/SRC/can_master/timescale.v
$HW_dir/SRC/checkpoint_ctrl/rtl/verilog/checkpoint_ctrl.v
$HW_dir/SRC/ecc_bch_dec/src/rtl/univ/bch_dec_dcd_univ_top.v
$HW_dir/SRC/ecc_bch_dec/src/rtl/univ/bch_dec_enc_univ_top.v
$HW_dir/SRC/ecc_bch_dec/src/rtl/univ/enc_synd_calc_univ.v
$HW_dir/SRC/ecc_bch_dec/src/rtl/univ/err_pat_dcd_rom_univ.v
//$HW_dir/SRC/ecc_bch_dec/src/sim/univ/dcd_univ_tb_top_n.v
$HW_dir/SRC/intgen/rtl/verilog/intgen.v
$HW_dir/SRC/jtag_tap_1.13/tap/rtl/verilog/tap_top.v
//$HW_dir/SRC/mor1kx_5.0-r1/bench/verilog/mor1kx_monitor.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/lockstep_aux/delay_unit.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx-defines.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx-sprs.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_branch_prediction.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_branch_predictor_gshare.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_branch_predictor_saturation_counter.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_branch_predictor_simple.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_bus_if_wb32.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cache_lru.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cfgrs.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cpu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cpu_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cpu_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cpu_prontoespresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_ctrl_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_ctrl_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_ctrl_prontoespresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_dcache.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_decode.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_decode_execute_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_dmmu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_execute_alu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_fetch_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_fetch_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_fetch_prontoespresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_icache.sv
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_immu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_lockstep_cpu_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_lsu_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_lsu_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_pcu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_pic.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_rf_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_rf_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_simple_dpram_sclk.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_store_buffer.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_ticktimer.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_true_dpram_sclk.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_wb_mux_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_wb_mux_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_addsub.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_cmp.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_f2i.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_i2f.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_muldiv.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_rnd.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_top.v
$HW_dir/SRC/parity_control/rtl/verilog/parity_ctrl.v
$HW_dir/SRC/safety_monitor/rtl/verilog/safety_monitor.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/raminfr.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_defines.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_receiver.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_regs.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_rfifo.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_sync_flops.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_tfifo.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_top.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_transmitter.v
$HW_dir/SRC/uart16550_1.5.4/rtl/verilog/uart_wb.v
$HW_dir/SRC/utils/verilog-arbiter_0-r1/src/arbiter.v
$HW_dir/TB/autosoc_tb.v
$HW_dir/TB/include/test-defines.v
$HW_dir/TB/jtag_vpi_0-r2/jtag_vpi.v
$HW_dir/TB/mor1kx_monitor.v
$HW_dir/TB/vlog_tb_utils_1.0/vlog_functions.v
$HW_dir/TB/vlog_tb_utils_1.0/vlog_tap_generator.v
$HW_dir/TB/vlog_tb_utils_1.0/vlog_tb_utils.v
