//$HW_dir/SRC/mor1kx_5.0-r1/bench/verilog/mor1kx_monitor.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/lockstep_aux/delay_unit.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx-defines.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx-sprs.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_branch_prediction.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_branch_predictor_gshare.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_branch_predictor_saturation_counter.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_branch_predictor_simple.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_bus_if_wb32.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cache_lru.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cfgrs.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cpu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cpu_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cpu_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_cpu_prontoespresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_ctrl_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_ctrl_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_ctrl_prontoespresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_dcache.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_decode.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_decode_execute_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_dmmu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_execute_alu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_fetch_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_fetch_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_fetch_prontoespresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_icache.sv
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_immu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_lockstep_cpu_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_lsu_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_lsu_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_pcu.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_pic.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_rf_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_rf_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_simple_dpram_sclk.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_store_buffer.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_ticktimer.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_true_dpram_sclk.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_wb_mux_cappuccino.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/mor1kx_wb_mux_espresso.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_addsub.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_cmp.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_f2i.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_i2f.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_muldiv.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_rnd.v
$HW_dir/SRC/mor1kx_5.0-r1/rtl/verilog/pfpu32/pfpu32_top.v

